### PR TITLE
Support for squash and merge

### PR DESCRIPTION
**Pull request by 304NotModified**
Supersedes https://github.com/lalitkapoor/github-changes/pull/62

test script:

```
npm uninstall -g github-changes
npm install -g https://github.com/304NotModified/github-changes/tarball/handle-squash-merge-2
github-changes -o nlog -r nlog -a --only-pulls --use-commit-body --date-format (YYYY/MM/DD)  
```

changedlog.md contains "allow different separator for Exception.Data (#1628) (@FroggieFrog)"

### CODE REVIEW

**Comment by lalitkapoor** [comment]
Thanks for working on this! I will give it a look.

**Comment by 304NotModified** [comment]
Works good for me anyway :)

**Comment by tkurki** [comment]
This produced a lot better (but not perfect) results for me. If it doesn't break existing functionality I'd urge you to merge it.

**Comment by lalitkapoor** [comment]
@tkurki Thanks for trying this out and for the feedback. Curious - what were the not perfect results for you?

**Comment by 304NotModified** [comment]
Don't think this will breaks something.

**Comment by tkurki** [comment]
At least https://github.com/SignalK/signalk-server-node/pull/138 is still missing from the result of `github-changes -o signalk -r signalk-server-node -a --only-pulls --use-commit-body`.

**Comment by 304NotModified** [comment]
Whats the commit message of the squash?

**Comment by lalitkapoor** [comment]
Have an idea - Lets put this behind a flag `--squash-and-merge` and put in the description that it's experimental (and what the signature of the commit message needs to include for it to get picked up).

I'm happy to start adding support for it, but because it does miss things I'm a little hesitant to have it enabled on by default.

If you can update with that I'll gladly pull it in :)

What do you think?

**Comment by 304NotModified** [comment]
This one is testing for  ' (#123)', but of course it's system dependent (eg github)

**Comment by tkurki** [comment]
Actually now that I reran the version off npm  with `--only-pulls --use-commit-body --data=pulls` I got a result that LGTM. I had overlooked --data=pulls, it being deprecated, and --only-pulls does not do the same thing.

**Comment by lalitkapoor** [comment]
@tkurki given that the `--data` is deprecated do one of the other options work? maybe `--only-merges`?

Would like to not support `--data` anymore.

**Comment by tkurki** [comment]
Well, my vote goes for not removing  --data=pulls until you have equivalent functionality available somehow.  I'm perfectly happy with the results.

Don't know about the other options.

https://github.com/lalitkapoor/github-changes/blob/master/bin/index.js#L513

**Comment by lalitkapoor** [comment]
@tkurki nice! I had forgotten that `--data=pulls` uses the github pull request api and not the commit api. That will actually catch all the pull requests :) regardless of the merge strategy. The one thing it won't be able to do though is give attribution to multiple committers, if there were any in that branch. I think this is an acceptable tradeoff though.

@304NotModified Your solution works for the case when `--data=commits` (the default), but depends on a `(#123)` in the commit message (which is what it defaults to in github). So, I'd like to merge your pull request in too. Do you mind adding a note in your pull request to the readme for how this library handles the squash and merge strategy?

Thank you both for looking into this and debugging this!

**Comment by 304NotModified** [comment]
> Do you mind adding a note in your pull request to the readme for how this library handles the squash and merge strategy?

Sure, but dunno where to add it. It's not "Installation" or "Example usage". Maybe adding a FAQ to the wiki is a better idea?

**Comment by lalitkapoor** [comment]
@304NotModified I think at the bottom of the readme we can start a FAQ section and this can be only thing in it for now.

**Comment by 304NotModified** [comment]
isn't the wiki a better place for it?

**Comment by lalitkapoor** [comment]
@304NotModified I think since there isn't a lot of content and I'd like for the user to get that information as easily and quickly as possible. I'm a fan of adding to the Readme till it no longer makes sense.

**Comment by 304NotModified** [comment]
I've added the FAQ. Please merge.

**Pull request merged**
