### PR TITLE
support for squash and merge

### PR DESCRIPTION
**Pull request by lalitkapoor**
to handle #60

### CODE REVIEW

**Comment by fixe** [comment]
Doesn't work for me -- I'll try to investigate further.

**Comment by lalitkapoor** [comment]
thanks @fixe I really appreciate you taking a look!

**Comment by 304NotModified** [comment]
yes it isn't working, also discussed here: https://github.com/lalitkapoor/github-changes/issues/60

I will try the my proposed regex

**Comment by 304NotModified** [comment]
Fixed in https://github.com/lalitkapoor/github-changes/pull/64

**Comment by tkurki** [comment]
Close this in favor of #64 ?

**Pull request merged**
