### PR TITLE
Update ghauth dependency

### PR DESCRIPTION
**Pull request by nunorafaelrocha**
This PR updates `ghauth` dependency that is causing some problems using GitHub two factor authentication.

### CODE REVIEW

**Comment by lalitkapoor** [comment]
thanks @nunorafaelrocha

**Comment by ricardogama** [comment]
@lalitkapoor Can you make a release with this fix?

**Comment by nunorafaelrocha** [comment]
@lalitkapoor +1 :smile:

**Comment by lalitkapoor** [comment]
released!

**Comment by nunorafaelrocha** [comment]
@lalitkapoor Sweet! :+1:

**Pull request merged**
